In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [24]:
df = pd.read_csv('gramediaCSV.csv', sep= ";", encoding='latin-1')

In [25]:
df.head(2)

,no_id,judul,author,penerbit,isBestSeller,original_rating,adjusted_rating,rating_count,review_count,genre,Unnamed: 10,Unnamed: 11
0,1,Game of Hearts: Love In Vegas,Silvarani,Gramedia Pustaka Utama,1,3.0,3.0,34.0,14.0,fiksi_sastra,NaN,NaN
1,2,My Nerd Girl,Aidah Harisah,Gramedia Widiasarana Indonesia,0,3.39,3.0,28.0,3.0,novel,NaN,NaN

In [26]:
df.shape

(2154, 12)

In [27]:
df.columns

Index(['no_id', 'judul', 'author', 'penerbit', 'isBestSeller',
       'original_rating', 'adjusted_rating', 'rating_count', 'review_count',
       'genre', 'Unnamed: 10', 'Unnamed: 11'],
      dtype='object')

In [99]:
df.rename(columns={
    "no_id": "NO_ID",
    "judul": "Judul",
    "author": "Penulis",
    "penerbit": "Penerbit",
    "isBestSeller": "BestSeller",
    "original_rating": "Original_Rating",
    "adjusted_rating": "Adjusted_Rating",
    "rating_count": "Rating_Count",
    "review_count": "Review_User",
    "genre": "Genre",
    
    
    
    
    
    
}, inplace =True)

df [['NO_ID', 'Judul', 'Penulis', 'Penerbit', 'BestSeller',
      'Adjusted_Rating', 'Rating_Count', 'Review_User',
       'Genre']]

,NO_ID,Judul,Penulis,Penerbit,BestSeller,Adjusted_Rating,Rating_Count,Review_User,Genre
0,1,Game of Hearts: Love In Vegas,Silvarani,Gramedia Pustaka Utama,1,3.0,34.0,14.0,fiksi_sastra
1,2,My Nerd Girl,Aidah Harisah,Gramedia Widiasarana Indonesia,0,3.0,28.0,3.0,novel
2,3,Harlequin Koleksi Istimewa: Dalam Dekapan Sang...,Annie West,Gramedia Pustaka Utama,1,3.0,240.0,40.0,romance
3,4,Harlequin Koleksi Istimewa: Sang Perencana Per...,Teresa Carpenter,Gramedia Pustaka Utama,0,4.0,33.0,10.0,novel
4,5,Konspirasi Alam Semesta,Fiersa Besari,Mediakita,1,4.0,4189.0,242.0,novel_lokal
...,...,...,...,...,...,...,...,...,...
2149,2150,The Orphan Train Vol. 1: Jim,Bamboo Media,Bhuana Ilmu Populer,0,4.0,95.0,NaN,novel_grafis
2150,2151,SI JUKI Seri Keroyokan Invasi Dimulai!,Pionicon,Bukune,0,4.0,88.0,0.0,novel_grafis
2151,2152,Pak Bei Sok Tahu,Masdi,Kepustakaan Populer Gramedia,0,3.0,7.0,NaN,novel_grafis
2152,2153,Juara - Cover Film,Hilman Hariwijaya,Gramedia Pustaka Utama,0,4.0,2.0,NaN,novel_grafis
2153,2154,Si Juki Seri Keroyokan Makin Rame Aja! #3,Pionicon,Bukune,0,3.0,5.0,NaN,novel_grafis

In [90]:
df.head(10)

,NO_ID,Judul,Penulis,Penerbit,BestSeller,Original_Rating,Adjusted_Rating,Rating_Count,Review_User,Genre,Unnamed: 10,Unnamed: 11,Original_Rating
0,1,Game of Hearts: Love In Vegas,Silvarani,Gramedia Pustaka Utama,1,3.0,3.0,34.0,14.0,fiksi_sastra,NaN,NaN,3.00
1,2,My Nerd Girl,Aidah Harisah,Gramedia Widiasarana Indonesia,0,3.39,3.0,28.0,3.0,novel,NaN,NaN,3.39
2,3,Harlequin Koleksi Istimewa: Dalam Dekapan Sang...,Annie West,Gramedia Pustaka Utama,1,3.46,3.0,240.0,40.0,romance,NaN,NaN,3.46
3,4,Harlequin Koleksi Istimewa: Sang Perencana Per...,Teresa Carpenter,Gramedia Pustaka Utama,0,3.7,4.0,33.0,10.0,novel,NaN,NaN,3.70
4,5,Konspirasi Alam Semesta,Fiersa Besari,Mediakita,1,4.35,4.0,4189.0,242.0,novel_lokal,NaN,NaN,4.35
5,6,Harlequin: Tiga Keajaiban (Three Christmas Wis...,Sheila Roberts,Gramedia Pustaka Utama,1,4.04,4.0,1420.0,194.0,romance,NaN,NaN,4.04
6,7,Harlequin: Terperangkap (Close Contact),Lori Foster,Gramedia Pustaka Utama,1,4.13,4.0,2433.0,382.0,romance,NaN,NaN,4.13
7,8,Historical Romance: To Seduce a Sinner (Rayuan...,Elizabeth Hoyt,Gramedia Pustaka Utama,1,3.88,4.0,10737.0,769.0,romance,NaN,NaN,3.88
8,9,Sekali Peristiwa Di Banten Selatan,Pramoedya Ananta Toer,Lentera Dipantara,1,3.72,4.0,779.0,NaN,fiksi_sastra,NaN,NaN,3.72
9,10,Larasati,Pramoedya Ananta Toer,Lentera Dipantara,1,3.7,4.0,1684.0,NaN,fiksi_sastra,NaN,NaN,3.70

In [112]:
df['Genre'].value_counts()

Genre
novel                894
fiksi_sastra         303
romance              174
pengembangan_diri    158
novel_grafis          83
cerpen                72
klasik                34
puisi                 22
horor                 12
sastra_indonesia      11
novel_lokal            9
fiksi_ilmiah           6
motivasi               3
1.0                    2
fiksi_sejarah          2
1                      2
16.0                   2
34                     1
71                     1
4                      1
bisnis_ekonomi         1
inspirasi              1
1077                   1
5                      1
43                     1
1492.0                 1
thriller               1
37                     1
21214                  1
63.0                   1
11.0                   1
41                     1
19                     1
275.0                  1
fantasi                1
agama                  1
7.0                    1
11                     1
2.0                    1
drama                  1
fiksi_populer          1
anak                   1
16                     1
Name: count, dtype: int64

In [116]:

# Select specific columns in the sorted DataFrame
selected_columns = ['Judul', 'Penulis', 'genre', 'Penerbit']

In [122]:
df.head(15)

,NO_ID,Judul,Penulis,Penerbit,BestSeller,Original_Rating,Adjusted_Rating,Rating_Count,Review_User,Genre,Unnamed: 10,Unnamed: 11,Original_Rating
0,1,Game of Hearts: Love In Vegas,Silvarani,Gramedia Pustaka Utama,1,3.0,3.0,34.0,14.0,fiksi_sastra,NaN,NaN,3.00
1,2,My Nerd Girl,Aidah Harisah,Gramedia Widiasarana Indonesia,0,3.39,3.0,28.0,3.0,novel,NaN,NaN,3.39
2,3,Harlequin Koleksi Istimewa: Dalam Dekapan Sang...,Annie West,Gramedia Pustaka Utama,1,3.46,3.0,240.0,40.0,romance,NaN,NaN,3.46
3,4,Harlequin Koleksi Istimewa: Sang Perencana Per...,Teresa Carpenter,Gramedia Pustaka Utama,0,3.7,4.0,33.0,10.0,novel,NaN,NaN,3.70
4,5,Konspirasi Alam Semesta,Fiersa Besari,Mediakita,1,4.35,4.0,4189.0,242.0,novel_lokal,NaN,NaN,4.35
5,6,Harlequin: Tiga Keajaiban (Three Christmas Wis...,Sheila Roberts,Gramedia Pustaka Utama,1,4.04,4.0,1420.0,194.0,romance,NaN,NaN,4.04
6,7,Harlequin: Terperangkap (Close Contact),Lori Foster,Gramedia Pustaka Utama,1,4.13,4.0,2433.0,382.0,romance,NaN,NaN,4.13
7,8,Historical Romance: To Seduce a Sinner (Rayuan...,Elizabeth Hoyt,Gramedia Pustaka Utama,1,3.88,4.0,10737.0,769.0,romance,NaN,NaN,3.88
8,9,Sekali Peristiwa Di Banten Selatan,Pramoedya Ananta Toer,Lentera Dipantara,1,3.72,4.0,779.0,NaN,fiksi_sastra,NaN,NaN,3.72
9,10,Larasati,Pramoedya Ananta Toer,Lentera Dipantara,1,3.7,4.0,1684.0,NaN,fiksi_sastra,NaN,NaN,3.70
10,11,Di Balik Tirai Aroma Karsa,Dewi Lestari,Bentang Pustaka,1,4.4,4.0,111.0,28.0,novel,NaN,NaN,4.40
11,12,Sepotong Senja untuk Pacarku,Seno Gumira Ajidarma,Gramedia Pustaka Utama,0,3.98,4.0,2253.0,NaN,cerpen,NaN,NaN,3.98
12,13,Liqomik,Iqomic,Salsabila,0,4.37,4.0,19.0,3.0,novel_grafis,NaN,NaN,4.37
13,14,Pembunuhan di Malam Natal (Hercule Poirot's Ch...,Agatha Christie,Gramedia Pustaka Utama,0,3.98,4.0,62374.0,NaN,novel,NaN,NaN,3.98
14,15,Kepada Cium,Joko Pinurbo,Gramedia Pustaka Utama,1,3.64,4.0,217.0,NaN,puisi,NaN,NaN,3.64

In [124]:
def update_buku(judul, penulis, genre, penerbit, new_judul, new_penulis, new_genre, new_penerbit):
    # Check if the book with the given attributes exists
    mask = (Buku['Judul'] == judul) & (Buku['Penulis'] == penulis) & (Buku['Genre'] == genre) & (Buku['Penerbit'] == penerbit)
    
    if Buku.loc[mask].empty:
        print("Book not found. No updates were made.")
    else:
        # Update the rows that match the specified conditions with the new values
        Buku.loc[mask, 'Judul'] = new_judul
        Buku.loc[mask, 'Penulis'] = new_penulis
        Buku.loc[mask, 'Genre'] = new_genre
        Buku.loc[mask, 'Penerbit'] = new_penerbit
        print("The book has been updated.")

# Example usage to update a specific book
update_buku(judul='Game of Hearts: Love In Vegas', penulis='Silvarani', genre='fiksi_sastra',
            penerbit='Gramedia Pustaka Utama', new_judul='New Judul', new_penulis='New Penulis',
            new_genre='New Genre', new_penerbit='New Penerbit')

# Print the updated 'Buku' DataFrame
print(Buku)

Book not found. No updates were made.
      NO_ID                                              Judul  \
0         1                                          New Judul
1         2                                       My Nerd Girl
2         3  Harlequin Koleksi Istimewa: Dalam Dekapan Sang...
3         4  Harlequin Koleksi Istimewa: Sang Perencana Per...
4         5                            Konspirasi Alam Semesta
...     ...                                                ...
2149   2150                       The Orphan Train Vol. 1: Jim
2150   2151             SI JUKI Seri Keroyokan Invasi Dimulai!
2151   2152                                   Pak Bei Sok Tahu
2152   2153                                 Juara - Cover Film
2153   2154          Si Juki Seri Keroyokan Makin Rame Aja! #3

                Penulis                        Penerbit BestSeller  \
0           New Penulis                    New Penerbit          1
1         Aidah Harisah  Gramedia Widiasarana Indonesia          0
2            Annie West          Gramedia Pustaka Utama          1
3      Teresa Carpenter          Gramedia Pustaka Utama          0
4         Fiersa Besari                       Mediakita          1
...                 ...                             ...        ...
2149       Bamboo Media             Bhuana Ilmu Populer          0
2150           Pionicon                          Bukune          0
2151              Masdi    Kepustakaan Populer Gramedia          0
2152  Hilman Hariwijaya          Gramedia Pustaka Utama          0
2153           Pionicon                          Bukune          0

      Original_Rating  Adjusted_Rating  Rating_Count  Review_User  \
0                3.00              3.0          34.0         14.0
1                3.39              3.0          28.0          3.0
2                3.46              3.0         240.0         40.0
3                3.70              4.0          33.0         10.0
4                4.35              4.0        4189.0        242.0
...               ...              ...           ...          ...
2149             3.85              4.0          95.0          NaN
2150             4.25              4.0          88.0          0.0
2151             3.00              3.0           7.0          NaN
2152             4.00              4.0           2.0          NaN
2153             3.20              3.0           5.0          NaN

             Genre Unnamed: 10 Unnamed: 11
0        New Genre         NaN         NaN
1            novel         NaN         NaN
2          romance         NaN         NaN
3            novel         NaN         NaN
4      novel_lokal         NaN         NaN
...            ...         ...         ...
2149  novel_grafis         NaN         NaN
2150  novel_grafis         NaN         NaN
2151  novel_grafis         NaN         NaN
2152  novel_grafis         NaN         NaN
2153  novel_grafis         NaN         NaN

[2154 rows x 12 columns]

In [125]:
def edit_book(judul, penulis, genre, penerbit):
    # Check if the book with the given attributes exists
    mask = (Buku['Judul'] == judul) & (Buku['Penulis'] == penulis) & (Buku['Genre'] == genre) & (Buku['Penerbit'] == penerbit)
    
    if Buku.loc[mask].empty:
        print("Book not found.")
    else:
        # Prompt the user to enter new values for the book attributes
        new_judul = input("Enter the new Judul: ")
        new_penulis = input("Enter the new Penulis: ")
        new_genre = input("Enter the new Genre: ")
        new_penerbit = input("Enter the new Penerbit: ")
        
        # Update the rows that match the specified conditions with the new values
        Buku.loc[mask, 'Judul'] = new_judul
        Buku.loc[mask, 'Penulis'] = new_penulis
        Buku.loc[mask, 'Genre'] = new_genre
        Buku.loc[mask, 'Penerbit'] = new_penerbit
        print("The book has been updated.")

# Example usage to edit a specific book
edit_book(judul='Game of Hearts: Love In Vegas', penulis='Silvarani', genre='fiksi_sastra',
          penerbit='Gramedia Pustaka Utama')

# Print the updated 'Buku' DataFrame
print(Buku)

Book not found.
      NO_ID                                              Judul  \
0         1                                          New Judul
1         2                                       My Nerd Girl
2         3  Harlequin Koleksi Istimewa: Dalam Dekapan Sang...
3         4  Harlequin Koleksi Istimewa: Sang Perencana Per...
4         5                            Konspirasi Alam Semesta
...     ...                                                ...
2149   2150                       The Orphan Train Vol. 1: Jim
2150   2151             SI JUKI Seri Keroyokan Invasi Dimulai!
2151   2152                                   Pak Bei Sok Tahu
2152   2153                                 Juara - Cover Film
2153   2154          Si Juki Seri Keroyokan Makin Rame Aja! #3

                Penulis                        Penerbit BestSeller  \
0           New Penulis                    New Penerbit          1
1         Aidah Harisah  Gramedia Widiasarana Indonesia          0
2            Annie West          Gramedia Pustaka Utama          1
3      Teresa Carpenter          Gramedia Pustaka Utama          0
4         Fiersa Besari                       Mediakita          1
...                 ...                             ...        ...
2149       Bamboo Media             Bhuana Ilmu Populer          0
2150           Pionicon                          Bukune          0
2151              Masdi    Kepustakaan Populer Gramedia          0
2152  Hilman Hariwijaya          Gramedia Pustaka Utama          0
2153           Pionicon                          Bukune          0

      Original_Rating  Adjusted_Rating  Rating_Count  Review_User  \
0                3.00              3.0          34.0         14.0
1                3.39              3.0          28.0          3.0
2                3.46              3.0         240.0         40.0
3                3.70              4.0          33.0         10.0
4                4.35              4.0        4189.0        242.0
...               ...              ...           ...          ...
2149             3.85              4.0          95.0          NaN
2150             4.25              4.0          88.0          0.0
2151             3.00              3.0           7.0          NaN
2152             4.00              4.0           2.0          NaN
2153             3.20              3.0           5.0          NaN

             Genre Unnamed: 10 Unnamed: 11
0        New Genre         NaN         NaN
1            novel         NaN         NaN
2          romance         NaN         NaN
3            novel         NaN         NaN
4      novel_lokal         NaN         NaN
...            ...         ...         ...
2149  novel_grafis         NaN         NaN
2150  novel_grafis         NaN         NaN
2151  novel_grafis         NaN         NaN
2152  novel_grafis         NaN         NaN
2153  novel_grafis         NaN         NaN

[2154 rows x 12 columns]

In [126]:
def delete_buku(df, judul, penulis, genre, penerbit):
    # Check if the book with the given attributes exists
    mask = (df['Judul'] == judul) & (df['Penulis'] == penulis) & (df['Genre'] == genre) & (df['Penerbit'] == penerbit)
    
    if df.loc[mask].empty:
        print("Book not found. No book was deleted.")
    else:
        # Remove the rows that match the specified conditions
        df = df.loc[~mask].reset_index(drop=True)
        print("The book has been deleted.")
    
    return df

# Example usage to delete a specific book
Buku = delete_buku(Buku, judul='Game of Hearts: Love In Vegas', penulis='Silvarani', genre='fiksi_sastra',
                   penerbit='Gramedia Pustaka Utama')

# Print the updated 'Buku' DataFrame after deleting the book
print(Buku)

Book not found. No book was deleted.
      NO_ID                                              Judul  \
0         1                                          New Judul
1         2                                       My Nerd Girl
2         3  Harlequin Koleksi Istimewa: Dalam Dekapan Sang...
3         4  Harlequin Koleksi Istimewa: Sang Perencana Per...
4         5                            Konspirasi Alam Semesta
...     ...                                                ...
2149   2150                       The Orphan Train Vol. 1: Jim
2150   2151             SI JUKI Seri Keroyokan Invasi Dimulai!
2151   2152                                   Pak Bei Sok Tahu
2152   2153                                 Juara - Cover Film
2153   2154          Si Juki Seri Keroyokan Makin Rame Aja! #3

                Penulis                        Penerbit BestSeller  \
0           New Penulis                    New Penerbit          1
1         Aidah Harisah  Gramedia Widiasarana Indonesia          0
2            Annie West          Gramedia Pustaka Utama          1
3      Teresa Carpenter          Gramedia Pustaka Utama          0
4         Fiersa Besari                       Mediakita          1
...                 ...                             ...        ...
2149       Bamboo Media             Bhuana Ilmu Populer          0
2150           Pionicon                          Bukune          0
2151              Masdi    Kepustakaan Populer Gramedia          0
2152  Hilman Hariwijaya          Gramedia Pustaka Utama          0
2153           Pionicon                          Bukune          0

      Original_Rating  Adjusted_Rating  Rating_Count  Review_User  \
0                3.00              3.0          34.0         14.0
1                3.39              3.0          28.0          3.0
2                3.46              3.0         240.0         40.0
3                3.70              4.0          33.0         10.0
4                4.35              4.0        4189.0        242.0
...               ...              ...           ...          ...
2149             3.85              4.0          95.0          NaN
2150             4.25              4.0          88.0          0.0
2151             3.00              3.0           7.0          NaN
2152             4.00              4.0           2.0          NaN
2153             3.20              3.0           5.0          NaN

             Genre Unnamed: 10 Unnamed: 11
0        New Genre         NaN         NaN
1            novel         NaN         NaN
2          romance         NaN         NaN
3            novel         NaN         NaN
4      novel_lokal         NaN         NaN
...            ...         ...         ...
2149  novel_grafis         NaN         NaN
2150  novel_grafis         NaN         NaN
2151  novel_grafis         NaN         NaN
2152  novel_grafis         NaN         NaN
2153  novel_grafis         NaN         NaN

[2154 rows x 12 columns]

In [128]:
edit_book(judul='Game of Hearts: Love In Vegas', penulis='Silvarani', genre='fiksi_sastra',
          penerbit='Gramedia Pustaka Utama')

Book not found.

In [134]:
from flask import Flask, request

app = Flask(__name__)

# Your other routes and code

@app.route('/submit_review', methods=['POST'])
def submit_review():
    if request.method == 'POST':
        book_id = int(request.form['book_id'])  # Assuming you have an input field named 'book_id'
        
        # Find the row in the DataFrame with the corresponding book_id
        book_row = df.loc[df['Book_ID'] == book_id]
        
        if not book_row.empty:
            # Increment the Review_User value by 1
            df.loc[df['Book_ID'] == book_id, 'Review_User'] += 1
            
            # Save the changes to the DataFrame (assuming you are using a persistent storage)
            # For example, if using a CSV file: df.to_csv('your_csv_file.csv', index=False)
            
            return "Review submitted successfully!"
        else:
            return "Book not found."
    else:
        return "Invalid request."


print(df)

      NO_ID                                              Judul  \
0         1                      Game of Hearts: Love In Vegas
1         2                                       My Nerd Girl
2         3  Harlequin Koleksi Istimewa: Dalam Dekapan Sang...
3         4  Harlequin Koleksi Istimewa: Sang Perencana Per...
4         5                            Konspirasi Alam Semesta
...     ...                                                ...
2149   2150                       The Orphan Train Vol. 1: Jim
2150   2151             SI JUKI Seri Keroyokan Invasi Dimulai!
2151   2152                                   Pak Bei Sok Tahu
2152   2153                                 Juara - Cover Film
2153   2154          Si Juki Seri Keroyokan Makin Rame Aja! #3

                Penulis                        Penerbit BestSeller  \
0             Silvarani          Gramedia Pustaka Utama          1
1         Aidah Harisah  Gramedia Widiasarana Indonesia          0
2            Annie West          Gramedia Pustaka Utama          1
3      Teresa Carpenter          Gramedia Pustaka Utama          0
4         Fiersa Besari                       Mediakita          1
...                 ...                             ...        ...
2149       Bamboo Media             Bhuana Ilmu Populer          0
2150           Pionicon                          Bukune          0
2151              Masdi    Kepustakaan Populer Gramedia          0
2152  Hilman Hariwijaya          Gramedia Pustaka Utama          0
2153           Pionicon                          Bukune          0

      Original_Rating  Adjusted_Rating  Rating_Count  Review_User  \
0                 3.0              3.0          34.0         14.0
1                3.39              3.0          28.0          3.0
2                3.46              3.0         240.0         40.0
3                 3.7              4.0          33.0         10.0
4                4.35              4.0        4189.0        242.0
...               ...              ...           ...          ...
2149             3.85              4.0          95.0          NaN
2150             4.25              4.0          88.0          0.0
2151              3.0              3.0           7.0          NaN
2152              4.0              4.0           2.0          NaN
2153              3.2              3.0           5.0          NaN

             Genre Unnamed: 10 Unnamed: 11  Original_Rating
0     fiksi_sastra         NaN         NaN             3.00
1            novel         NaN         NaN             3.39
2          romance         NaN         NaN             3.46
3            novel         NaN         NaN             3.70
4      novel_lokal         NaN         NaN             4.35
...            ...         ...         ...              ...
2149  novel_grafis         NaN         NaN             3.85
2150  novel_grafis         NaN         NaN             4.25
2151  novel_grafis         NaN         NaN             3.00
2152  novel_grafis         NaN         NaN             4.00
2153  novel_grafis         NaN         NaN             3.20

[2154 rows x 13 columns]

In [135]:
# Assuming you have a DataFrame named df

book_id = 123  # Replace with the actual book ID you want to update

# Find the row index in the DataFrame with the corresponding book_id
book_index = df.index[df['Book_ID'] == book_id].tolist()

if len(book_index) == 1:
    # Increment the Review_User value by 1
    df.loc[book_index, 'Review_User'] += 1
    
    # Display the updated DataFrame
    print(df)
    
    # Save the changes to the DataFrame (if applicable)
    # For example, if using a persistent storage like a CSV file: df.to_csv('your_csv_file.csv', index=False)
else:
    print("Book not found.")

KeyError: 'Book_ID'

In [136]:
import pandas as pd

# Load the CSV into a DataFrame
df = pd.read_csv('gramediaCSV.csv', sep=';', encoding='latin-1')

# Make changes to the DataFrame
book_id_to_update = 123  # Replace with the actual book ID you want to update
new_review_user_value = 10  # Replace with the new Review_User value

# Find the index of the row with the specified book_id
index_to_update = df.index[df['Book_ID'] == book_id_to_update].tolist()

if len(index_to_update) == 1:
    df.loc[index_to_update, 'Review_User'] = new_review_user_value

    # Save the DataFrame back to the CSV file
    df.to_csv('gramediaCSV.csv', sep=';', index=False, encoding='latin-1')
else:
    print("Book not found.")
Remember to replace 123 with the actual book_id you want to update and 10 with the new Review_User value.

Keep in mind that while this approach is straightforward, it may not be efficient for large datasets. If you're working with large datasets, consider more advanced techniques such as using a database or more specialized libraries for CSV manipulation.

Also, be cautious when directly modifying files, especially if multiple processes or users might access the file simultaneously. It's a good practice to make backups and implement proper error handling.

SyntaxError: unterminated string literal (detected at line 22) (4114250329.py, line 22)

In [32]:
df.head(129)

,no_id,judul,author,penerbit,isBestSeller,original_rating,adjusted_rating,rating_count,review_count,genre,Unnamed: 10,Unnamed: 11
0,1,Game of Hearts: Love In Vegas,Silvarani,Gramedia Pustaka Utama,1,3.0,3.0,34.0,14.2,fiksi_sastra,NaN,NaN
1,2,My Nerd Girl,Aidah Harisah,Gramedia Widiasarana Indonesia,0,3.39,3.0,28.0,3.0,novel,NaN,NaN
2,3,Harlequin Koleksi Istimewa: Dalam Dekapan Sang...,Annie West,Gramedia Pustaka Utama,1,3.46,3.0,240.0,40.0,romance,NaN,NaN
3,4,Harlequin Koleksi Istimewa: Sang Perencana Per...,Teresa Carpenter,Gramedia Pustaka Utama,0,3.7,4.0,33.0,10.0,novel,NaN,NaN
4,5,Konspirasi Alam Semesta,Fiersa Besari,Mediakita,1,4.35,4.0,4189.0,242.0,novel_lokal,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
124,125,Sketsa Terakhir,Kei Larasati,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,126,Silver Stone,Ardina Hasanbasri,Serambi Ilmu Semesta,0,3.42,3.0,26.0,NaN,fiksi_sastra,NaN,NaN
126,127,SANG PENCERAH,Akmal Nasery Basral,Mizan,0,4.0,4.0,223.0,37.0,fiksi_sastra,NaN,NaN
127,128,Running For Hope,Dona Sikoembang,Mizan,0,3.35,3.0,78.0,NaN,fiksi_sastra,NaN,NaN
128,129,Prodigy A legend Novel,Marie Lu,Mizan,0,4.24,4.0,242105.0,NaN,fiksi_sastra,NaN,NaN

In [31]:
import pandas as pd

# Load the CSV into a DataFrame
df = pd.read_csv('gramediaCSV.csv', sep=';', encoding='latin-1')

# Assuming you have a form where the user submits the book ID
submitted_book_id = 1  # Replace with the actual book ID submitted by the user

# Find the index of the row with the submitted book ID
index_to_update = df.index[df['no_id'] == submitted_book_id].tolist()

if len(index_to_update) == 1:
    print(f"Found index_to_update: {index_to_update}")
    # Increment the review_count in the DataFrame
    df.loc[index_to_update[0], 'review_count'] += 0.1
    print(f"Updated review_count: {df.loc[index_to_update[0], 'review_count']}")

    try:
        # Save the updated DataFrame back to the CSV file
        df.to_csv('gramediaCSV.csv', sep=';', index=False, encoding='latin-1')
        print("Review count updated and saved successfully!")
    except Exception as e:
        print("Error while saving DataFrame to CSV:", e)

    # Save the updated DataFrame back to the CSV file
    df.to_csv('gramediaCSV.csv', sep=';', index=False, encoding='latin-1')
    print("Review count updated successfully!")
else:
    print("Book not found.")

Review count updated successfully!

In [9]:
df.columns

Index(['no_id', 'judul', 'author', 'penerbit', 'isBestSeller',
       'original_rating', 'adjusted_rating', 'rating_count', 'review_count',
       'genre', 'Unnamed: 10', 'Unnamed: 11'],
      dtype='object')

In [27]:
df['review_count'].value_counts()

review_count
1.0       23
3.0       21
4.0       17
0.0       17
2.0       14
          ..
85.0       1
110.0      1
1645.0     1
146.0      1
94.0       1
Name: count, Length: 125, dtype: int64